# Generated by Django 5.2.4 on 2025-07-28 19:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='knowledgesource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='api_endpoint',
            field=models.URLField(blank=True, help_text='For API type', null=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='api_headers',
            field=models.JSONField(blank=True, default=dict, help_text='Headers for API requests'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='api_params',
            field=models.JSONField(blank=True, default=dict, help_text='Parameters for API requests'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='auto_refresh',
            field=models.BooleanField(default=False, help_text='Auto-refresh content periodically'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='database_config',
            field=models.JSONField(blank=True, default=dict, help_text='Database connection config'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if indexing failed'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('xlsx', 'Excel Spreadsheet'), ('pptx', 'PowerPoint'), ('txt', 'Text File'), ('csv', 'CSV File'), ('json', 'JSON File'), ('xml', 'XML File'), ('html', 'HTML File'), ('md', 'Markdown File')], max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='integration_config',
            field=models.JSONField(blank=True, default=dict, help_text='Config for integrations like Slack, Notion, etc.'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='last_refreshed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='refresh_interval_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours between auto-refresh'),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, help_text='Content size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='url',
            field=models.URLField(blank=True, help_text='For URL, API, RSS_FEED types', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional message metadata'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='content',
            field=models.TextField(blank=True, help_text='For TEXT type or metadata'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='type',
            field=models.CharField(choices=[('URL', 'URL'), ('FILE', 'File'), ('TEXT', 'Text'), ('DATABASE', 'Database'), ('API', 'API'), ('SPREADSHEET', 'Spreadsheet'), ('CONFLUENCE', 'Confluence'), ('NOTION', 'Notion'), ('SLACK', 'Slack'), ('GOOGLE_DRIVE', 'Google Drive'), ('SHAREPOINT', 'SharePoint'), ('GITHUB', 'GitHub'), ('JIRA', 'JIRA'), ('RSS_FEED', 'RSS Feed'), ('EMAIL', 'Email')], max_length=20),
        ),
        migrations.CreateModel(
            name='KnowledgeSourceRefresh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('changes_detected', models.BooleanField(default=False)),
                ('knowledge_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_logs', to='core.knowledgesource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
