# Generated by Django 5.2.4 on 2025-07-29 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apiusage_systemhealth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='system_prompt',
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_goal',
            field=models.TextField(blank=True, help_text='What is the primary objective of this agent?'),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_instructions',
            field=models.TextField(blank=True, help_text='Provide detailed, step-by-step instructions for the agent.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_role',
            field=models.TextField(blank=True, default='You are a helpful customer support assistant.', help_text="Define the agent's persona or role (e.g., 'You are a friendly pirate...')."),
        ),
        migrations.AddField(
            model_name='agent',
            name='examples',
            field=models.TextField(blank=True, help_text="Optional few-shot examples in 'User: ...\\nAI: ...' format.", null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of what this agent does.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model',
            field=models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini'), ('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo'), ('gemini/gemini-1.5-pro-latest', 'Gemini 1.5 Pro'), ('gemini/gemini-1.5-flash-latest', 'Gemini 1.5 Flash'), ('claude-3-sonnet-20240229', 'Claude 3 Sonnet'), ('claude-3-haiku-20240307', 'Claude 3 Haiku')], default='gpt-4o-mini', max_length=50),
        ),
    ]
