# Generated by Django 5.2.4 on 2025-07-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_conversation_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='end_user_id',
            field=models.CharField(help_text='Session ID or unique identifier for the end-user', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10, null=True),
        ),
    ]
