# Generated by Django 5.2.4 on 2025-07-27 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_conversation_end_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='model',
            field=models.CharField(choices=[('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-3.5-turbo', help_text='The underlying language model for your agent.', max_length=50),
        ),
        migrations.AddField(
            model_name='agent',
            name='temperature',
            field=models.FloatField(default=0.2, help_text='Controls randomness (0.0 to 1.0). Lower is more predictable, higher is more creative.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
