# Generated by Django 5.2.4 on 2025-07-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_agent_model_agent_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='lyzr_agent_id',
            field=models.CharField(blank=True, help_text='The agent ID returned from the Lyzr Studio API', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a helpful and friendly customer support assistant.', help_text='The core personality and instructions for your agent.'),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='type',
            field=models.CharField(choices=[('URL', 'URL'), ('FILE', 'File'), ('FAQ', 'Text')], max_length=10),
        ),
    ]
