# Generated by Django 5.2.4 on 2025-07-27 14:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agent_lyzr_agent_id_alter_agent_system_prompt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgesource',
            name='agent',
        ),
        migrations.AlterField(
            model_name='agent',
            name='lyzr_agent_id',
            field=models.CharField(blank=True, help_text='The agent ID from the Lyzr Agent API', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='model',
            field=models.CharField(choices=[('gpt-4-turbo', 'GPT-4 Turbo'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo')], default='gpt-3.5-turbo', max_length=50),
        ),
        migrations.AlterField(
            model_name='agent',
            name='system_prompt',
            field=models.TextField(blank=True, default='You are a helpful customer support assistant.'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='temperature',
            field=models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='knowledgesource',
            name='type',
            field=models.CharField(choices=[('URL', 'URL'), ('FILE', 'File'), ('TEXT', 'Text')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rag_config_id', models.CharField(blank=True, help_text='The config_id from the Lyzr RAG API', max_length=255, null=True, unique=True)),
                ('collection_name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='core.agent')),
            ],
        ),
        migrations.AddField(
            model_name='knowledgesource',
            name='knowledge_base',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='core.knowledgebase'),
            preserve_default=False,
        ),
    ]
