# Generated by Django 5.2.4 on 2025-07-27 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_knowledgesource_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='top_p',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
