# Generated by Django 5.2.4 on 2025-07-27 18:58

import lyzr_backend.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_agent_top_p'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgesource',
            name='file',
            field=models.FileField(blank=True, null=True, storage=lyzr_backend.storages.source_storage(), upload_to=''),
        ),
    ]
